[versions]
agp = "9.0.0"
android-volley = "1.2.1"
appcompat = "1.7.1"
commons-codec = "1.20.0"
markwon-core = "4.6.2"
core-ktx = "1.17.0"
gson = "2.13.2"
kotlinx-coroutines-android = "1.10.2"
material = "1.13.0"
kotlin = "2.3.0"
preference-ktx = "1.2.1"
preference = "1.2.1"
swiperefreshlayout = "1.2.0"

[libraries]
android-volley = { module = "com.android.volley:volley", version.ref = "android-volley" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon-core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
